### ISSUE TITLE
UI: Add Price and ticket link

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#55]
Slide 24 of wireframes

This is a replica of the Caligram Admin tool for entering prices.

![Image](https://user-images.githubusercontent.com/419491/175302738-121293d1-e522-4d9a-b09d-10e7da7b3434.png)

**Comment by troughc** [comment]
Tested on SAFARI and CHROME
added a free event : PASS
added a paid price : PASS
All fields there: YES

When you go back in to the PRICE dialog to change price: it is no longer prefilled so you would start from scratch. You can do this and save - the new information replaces the old

ISSUE/BUG: When you go back in the PRICE pop-up dialog to modify or create a new price and click CANCEL, nothing happens. You can click the x to close the dialog.
Expected behaviour is that when you click CANCEL, the dialog would close and whatever was already in the Price would remain unchanged.

**Comment by troughc** [comment]
PASS!
